name: indentation

on: [ push, pull_request]

jobs:
  indentation:
    strategy: # remove?
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # reuse tests.yml or depend on it to not have to setup OCaml? https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow

      # rely on cache for now
      - name: Cache opam switch # https://github.com/marketplace/actions/cache
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.opam
            _opam
          # An explicit key for restoring and saving the cache
          key: opam-ocp-indent-${{ runner.os }}-${{ matrix.ocaml-compiler }}

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install ocp-indent
        run: opam install -y ocp-indent

      - name: Run pre-commit hook on changes since last push
        run: git reset --soft ${{ github.event.before }} && ./scripts/hooks/pre-commit
