name: build and run tests
# https://github.com/ocaml/setup-ocaml

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-compiler:
          - 4.12.0
          - 4.07.1
          # - 4.09.1
          # - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        env:
          # otherwise setup-ocaml pins non-locked dependencies
          # https://github.com/ocaml/setup-ocaml/issues/166
          OPAMLOCKED: locked
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      # Split build and tests into separate jobs and let build job upload the goblint binary as an artifact?
      # https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow

      - name: Install opam dependencies
        run: opam install . --deps-only --locked

      - name: Build
        run: ./make.sh nat

      - name: Run regression tests
        run: ./make.sh headers testci

      - name: Run octapron regression tests # skipped by default but CI has apron, so explicitly test group (which ignores skipping -- it's now a feature!)
        run: ruby scripts/update_suite.rb group octapron -s

      - name: Run domain tests
        run: |
          ./make.sh domaintest
          ./goblint.domaintest

      - name: Test Marshaling
        run: |
          ./make.sh
          ruby scripts/update_suite.rb -m
